import antfu from '@antfu/eslint-config'

export default antfu({
  stylistic: true,
  jsonc: true,

  vue: {
    vueVersion: 3,
    overrides: {
      'vue/no-v-html': 'error',
      'vue/valid-v-slot': 'error',
      'eqeqeq': 'error',
      'style/no-mixed-operators': 'error',
      'max-lines': ['error', 500],
      'vue/max-attributes-per-line': [
        'error',
        {
          singleline: {
            max: 1,
          },
          multiline: {
            max: 1,
          },
        },
      ],
      'vue/prefer-import-from-vue': 'error',
      'vue/multiline-ternary': 'error',
      // 'vue/no-bare-strings-in-template': 'error',
      'no-shadow': 'error',
      'vue/singleline-html-element-content-newline': 'error',
      'vue/block-order': 'error',
      'vue/block-tag-newline': 'error',
      'vue/component-api-style': 'error',
      'vue/component-name-in-template-casing': 'error',
      'vue/component-options-name-casing': 'error',
      'vue/custom-event-name-casing': 'error',
      'vue/define-emits-declaration': 'error',
      'vue/define-macros-order': 'error',
      'vue/define-props-declaration': 'error',
      'vue/html-button-has-type': 'error',
      'vue/html-comment-content-newline': 'error',
      'vue/html-comment-content-spacing': 'error',
      'vue/html-comment-indent': 'error',
      'vue/match-component-file-name': 'error',
      'vue/match-component-import-name': 'error',
      'vue/max-lines-per-block': 'error',
      'vue/new-line-between-multi-line-property': 'error',
      'vue/next-tick-style': 'error',
      'vue/no-boolean-default': 'error',
      'vue/no-deprecated-model-definition': 'error',
      'vue/no-duplicate-attr-inheritance': 'error',
      'vue/no-empty-component-block': 'error',
      'vue/no-multiple-objects-in-class': 'error',
      'vue/no-potential-component-option-typo': 'error',
      'vue/no-ref-object-reactivity-loss': 'error',
      'vue/no-required-prop-with-default': 'error',
      'vue/no-restricted-block': 'error',
      'vue/no-restricted-call-after-await': 'error',
      'vue/no-restricted-class': 'error',
      'vue/no-restricted-component-names': 'error',
      'vue/no-restricted-component-options': 'error',
      'vue/no-restricted-custom-event': 'error',
      'vue/no-restricted-html-elements': 'error',
      'vue/no-restricted-props': 'error',
      'vue/no-restricted-static-attribute': 'error',
      'vue/no-restricted-v-bind': 'error',
      'vue/no-setup-props-reactivity-loss': 'error',
      'vue/no-template-target-blank': 'error',
      'vue/no-this-in-before-route-enter': 'error',
      'vue/no-unsupported-features': 'error',
      'vue/no-unused-properties': 'error',
      'vue/no-unused-refs': 'error',
      'vue/no-useless-mustaches': 'error',
      'vue/no-useless-v-bind': 'error',
      'vue/no-v-text': 'error',
      'vue/padding-line-between-blocks': 'error',
      'vue/padding-line-between-tags': 'error',
      'vue/padding-lines-in-component-definition': 'error',
      'vue/prefer-define-options': 'error',
      'vue/prefer-prop-type-boolean-first': 'error',
      'vue/prefer-separate-static-class': 'error',
      'vue/prefer-true-attribute-shorthand': 'error',
      'vue/require-direct-export': 'error',
      'vue/require-emit-validator': 'error',
      'vue/require-expose': 'error',
      'vue/require-macro-variable-name': 'error',
      'vue/require-name-property': 'error',
      'vue/require-typed-object-prop': 'error',
      'vue/require-typed-ref': 'error',
      'vue/static-class-names-order': 'error',
      'vue/v-for-delimiter-style': 'error',
      'vue/valid-define-options': 'error',
      'vue/array-bracket-newline': ['error', 'always'],
      'vue/array-bracket-spacing': 'error',
      'vue/array-element-newline': ['error', 'always'],
      'vue/arrow-spacing': 'error',
      'vue/block-spacing': 'error',
      'vue/brace-style': 'error',
      'vue/camelcase': 'error',
      'vue/dot-location': 'error',
      'vue/dot-notation': 'error',
      'vue/eqeqeq': 'error',
      'vue/func-call-spacing': 'error',
      'vue/key-spacing': 'error',
      'vue/keyword-spacing': 'error',
      'vue/no-console': 'error',
      'vue/no-constant-condition': 'error',
      'vue/no-empty-pattern': 'error',
      'vue/no-extra-parens': 'error',
      'vue/no-irregular-whitespace': 'error',
      'vue/no-loss-of-precision': 'error',
      'vue/no-restricted-syntax': 'error',
      'vue/no-sparse-arrays': 'error',
      'vue/no-useless-concat': 'error',
      'vue/object-curly-newline': 'error',
      'vue/object-curly-spacing': 'error',
      'vue/object-property-newline': 'error',
      'vue/object-shorthand': 'error',
      'vue/operator-linebreak': 'error',
      'vue/prefer-template': 'error',
      'vue/quote-props': 'error',
      'vue/space-in-parens': 'error',
      'vue/space-infix-ops': 'error',
      'vue/space-unary-ops': 'error',
      'vue/template-curly-spacing': 'error',
      'vue/require-prop-types': 'error',
    },
  },
  typescript: {
    overrides: {
      'require-atomic-updates': 'error',
      'ts/ban-ts-comment': 'error',
      'eqeqeq': 'error',
      'style/no-mixed-operators': 'error',
      'ts/unified-signatures': 'error',
      'no-await-in-loop': 'error',
      'no-shadow': 'error',
      'consistent-return': 'error',
      'implicit-arrow-linebreak': 'error',
      'multiline-ternary': 'error',
      'newline-before-return': 'error',
      'no-confusing-arrow': 'error',
      'no-unsafe-optional-chaining': 'error',
      'require-await': 'error',
      'vue/require-typed-ref': 'error',
    },
  },
},
)
